name: sports_meet
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7+4
  image_cropper: ^1.2.3
  geolocator: ^5.3.2+2
  cloud_firestore: ^0.13.7
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/